# Generated by Django 2.2.1 on 2019-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(default=0, verbose_name='商品单价'),
            preserve_default=False,
        ),
    ]
