# Generated by Django 2.2.1 on 2019-09-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
