# Generated by Django 2.2.1 on 2019-09-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_cart_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder'),
            preserve_default=False,
        ),
    ]
