# Generated by Django 2.2.1 on 2019-09-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_cart_payorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payorder',
        ),
    ]
