# Generated by Django 2.2.1 on 2019-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_remove_cart_payorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
