# Generated by Django 2.2.1 on 2019-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_auto_20190928_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
