# Generated by Django 2.2.1 on 2019-09-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_type',
            new_name='goods_status',
        ),
    ]
