# Generated by Django 2.2.1 on 2019-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0006_auto_20190925_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='youbian',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
