# Generated by Django 2.2.1 on 2019-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0008_valid_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='youbian',
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户姓名')),
                ('adderss_detail', models.TextField(verbose_name='详细地址')),
                ('u_code', models.CharField(max_length=11, verbose_name='邮编')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('status', models.IntegerField(verbose_name='地址状态')),
                ('user', models.ManyToManyField(to='Saller.LoginUser')),
            ],
        ),
    ]
