# Generated by Django 2.2.1 on 2019-10-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0009_auto_20191009_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Saller.LoginUser'),
            preserve_default=False,
        ),
    ]
